### PR TITLE
can test if a document exists with the get_existing_or_empty

### PR DESCRIPTION
**Pull request by CedricCouton**
My need is to can call a function to test the document existence from it's id.
I can use the get existing and analyse the C4Error (not found) but it's not beautiful for me
I can add a get_existing_or_empty (my PR) and call the exists function (https://github.com/Dushistov/couchbase-lite-rust/pull/45) on the Document to test it's existence. More sexy but not the best
Or I can add a get_document with a Result<Option<Document>> as result. It's seem to be the best

What do you think ?

### CODE REVIEW

**Comment by Dushistov** [comment]
> My need is to can call a function to test the document existence from it's id.

Why not just run SQL code for this? Something like (pseudo code) `SELECT _id=x LIMIT 1`?

**Comment by CedricCouton** [comment]
Yes I can, but it's always better to have a library which dot it and have a simple function to do that no ?

**Comment by Dushistov** [comment]
I am afraid that it would be misleading function. For database that run synchronization task in the background
constantly the value of `is_delete` from cached document is not something that you can rely on.
To get proper value you need re-read document every time before calling `is_delete`.

If you want read list of documents and then show to user only not deleted one,
you can subscribe to replicator events and then get list of "not deleted" documents, and constantly 
in replicator callback remove deleted one from the list. Replicator callback has special flag `is_deleted` or something like this
for exactly this purpose if I remember correctly.

Delay in review is related to this fears. I need to read
couchbase-lite-java or couchbase-lite-ios to see how the implement this functionality,
and how they expect user to use it.

**Comment by CedricCouton** [comment]
Which function should be misleading ? get_existing_or_empty ?

**Comment by CedricCouton** [comment]
Ok. What is your comment about this PR ?

**Comment by CedricCouton** [comment]
What about case of : delete a doc and find a doc by get_document, the doc is returned or not ?

**Pull request closed without merging**
